# Generated by Django 3.1 on 2020-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moradores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
    ]
