# Generated by Django 3.1 on 2020-10-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moradores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('identidade', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('natural', models.CharField(max_length=30)),
                ('estadocivil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viuvo'), ('União Estavel', 'União Estavel')], max_length=15)),
                ('profissao', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
