# Generated by Django 3.1 on 2020-11-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moradores',
            name='cpf',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='moradores',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
