# Generated by Django 3.1 on 2020-08-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moradores',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
