# Generated by Django 3.1 on 2020-08-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0002_moradores_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moradores',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
