# Generated by Django 3.1 on 2020-09-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0003_auto_20200831_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='moradores',
            name='estadocivil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viuvo'), ('União Estavel', 'União Estavel')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moradores',
            name='identidade',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moradores',
            name='natural',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moradores',
            name='profissao',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
