# Generated by Django 3.1 on 2020-10-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Desocupado', 'Desocupado')], max_length=10)),
                ('fins', models.CharField(choices=[('Aluguel', 'Aluguel')], max_length=10)),
                ('cep', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('garagem', models.IntegerField()),
                ('quartos', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
