# Generated by Django 3.1 on 2020-09-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='importImoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ImageField(upload_to='arquivos')),
            ],
        ),
    ]
