# Generated by Django 3.1 on 2020-10-28 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historico_contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcontrato', models.CharField(max_length=15)),
                ('aluguel', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('morador', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo')], max_length=15)),
                ('data_entrada', models.DateField()),
                ('vigencia', models.IntegerField()),
                ('vencimento', models.DateField()),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('userid', models.IntegerField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imoveis.imovel', verbose_name='Imoveis')),
            ],
        ),
    ]
