# Generated by Django 3.1 on 2020-10-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietarios',
            old_name='endereco',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='password2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
