# Generated by Django 3.1 on 2020-10-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0002_auto_20201009_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietarios',
            old_name='nome',
            new_name='username',
        ),
    ]
