# Generated by Django 3.1 on 2020-10-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0003_auto_20201009_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietarios',
            name='bairro',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='cep',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='cidade',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='cpf',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='endereco',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='estado',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='identidade',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='numero',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='telefone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='userid',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
