# Generated by Django 3.1 on 2020-10-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0004_auto_20201010_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proprietarios',
            name='password',
        ),
        migrations.RemoveField(
            model_name='proprietarios',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='proprietarios',
            name='username',
        ),
    ]
