# Generated by Django 3.1 on 2020-10-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0005_auto_20201011_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietarios',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='password2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietarios',
            name='username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
