# Generated by Django 3.1 on 2020-10-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0006_auto_20201011_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietarios',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
