# Generated by Django 3.1 on 2020-10-28 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manutencao', 'Manutenção'), ('agua ', 'Água'), ('eletricidade ', 'Eletricidade'), ('imposto ', 'Imposto'), ('outro ', 'Outro')], max_length=25)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('observacao', models.TextField()),
                ('userid', models.IntegerField()),
                ('imoveis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imoveis.imovel')),
            ],
        ),
    ]
