# Generated by Django 3.1 on 2020-11-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='nota_fiscal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='tipo',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('Água', 'Água'), ('Eletricidade', 'Eletricidade'), ('Imposto', 'Imposto'), ('Outro', 'Outro')], max_length=25),
        ),
    ]
