# Generated by Django 3.1 on 2020-09-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesas',
            old_name='id_user',
            new_name='userid',
        ),
    ]
