# Generated by Django 3.1 on 2020-09-02 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0002_imovel_userid'),
        ('moradores', '0003_auto_20200831_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcontrato', models.CharField(max_length=15)),
                ('aluguel', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data_entrada', models.DateField()),
                ('vigencia', models.IntegerField()),
                ('vencimento', models.DateField()),
                ('userid', models.IntegerField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imoveis.imovel', verbose_name='Imoveis')),
                ('morador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moradores.moradores')),
            ],
        ),
    ]
