# Generated by Django 3.1 on 2020-09-27 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2020, 9, 26, 22, 40, 7, 121963))),
                ('documento', models.ImageField(upload_to='documentos')),
                ('contrato', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2020, 9, 26, 22, 40, 7, 122962))),
                ('foto', models.ImageField(upload_to='imagens')),
                ('contrato', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='contrato',
            name='aluguel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
