# Generated by Django 3.1 on 2020-09-27 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_auto_20200926_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 23, 23, 17, 801088)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 23, 23, 17, 802088)),
        ),
    ]
