# Generated by Django 3.1 on 2020-10-31 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_auto_20201030_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 10, 31, 18, 10, 30, 480982)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 10, 31, 18, 10, 30, 481981)),
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contratos_contrato',
        ),
    ]
