# Generated by Django 3.1 on 2020-11-01 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_auto_20201101_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 11, 1, 16, 50, 50, 549322)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 11, 1, 16, 50, 50, 550325)),
        ),
    ]
