# Generated by Django 3.1 on 2020-09-27 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_auto_20200927_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 27, 0, 15, 29, 317)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 27, 0, 15, 29, 1316)),
        ),
    ]
