# Generated by Django 3.1 on 2020-11-02 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_auto_20201101_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 11, 1, 21, 2, 30, 194199)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 11, 1, 21, 2, 30, 195197)),
        ),
    ]
