# Generated by Django 3.1 on 2020-11-02 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_auto_20201101_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 11, 2, 11, 47, 57, 890841)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 11, 2, 11, 47, 57, 890841)),
        ),
    ]
