# Generated by Django 3.1 on 2020-09-28 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_auto_20200928_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 20, 1, 30, 703962)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 20, 1, 30, 705960)),
        ),
    ]
