# Generated by Django 3.1 on 2020-09-30 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_auto_20200928_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 29, 21, 42, 43, 909319)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 29, 21, 42, 43, 910318)),
        ),
    ]
