# Generated by Django 3.1 on 2020-10-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0039_auto_20201012_1425'),
        ('contratos', '0039_auto_20201013_1950'),
    ]

    operations = [
    ]
