# Generated by Django 3.1 on 2020-10-19 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0051_auto_20201018_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 10, 18, 22, 13, 27, 13216)),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 10, 18, 22, 13, 27, 14215)),
        ),
    ]
